export const CANVAS_CONFIG = {
  CHUNK_SIZE: 4000,
  CULLING_PADDING: 1000,
  MAX_SCROLL_SPEED: 8,
  INTERPOLATION_FACTOR: 0.08,
  FRICTION: 0.92,
  MIN_VELOCITY: 0.1,
  DRAG_FACTOR: 0.4,
  WHEEL_FACTOR: 0.8,
  KEYBOARD_FACTOR: 30,
  TOUCH_FACTOR: 0.6,
  PARALLAX_DEPTHS: 3,
  IMAGE_LOAD_PRIORITY_DISTANCE: 500,
  MAX_CACHED_IMAGES: 100,
  PRELOAD_CHUNK_RADIUS: 2,
  ZOOM_MIN: 0.5,
  ZOOM_MAX: 2,
  ZOOM_STEP: 0.02,
  ZOOM_FRICTION: 0.9,
  MOTION_BLUR_MAX: 15,
  MOTION_BLUR_FACTOR: 0.3,
  TRANSITION_DURATION: 0.8,
  ASSET_RETRY_COUNT: 3,
  ASSET_RETRY_DELAY: 1000,
  RENDER_MODE: 'webgl' as const,
  QUALITY: {
    LOW: 0.5,
    MEDIUM: 0.75,
    HIGH: 1,
  },
};

export const ARTWORK_ASPECT_RATIOS = [
  { width: 4, height: 3 },
  { width: 3, height: 4 },
  { width: 16, height: 9 },
  { width: 9, height: 16 },
  { width: 1, height: 1 },
  { width: 3, height: 2 },
  { width: 2, height: 3 },
  { width: 5, height: 4 },
];

export const CANVAS_IMAGES = [
  {
    id: 'art-1',
    src: 'https://images.unsplash.com/photo-1549490349-8643362247b5?w=800&q=80',
    title: 'Ethereal Horizons',
    artist: 'Maya Chen',
    year: '2024',
    description: 'An exploration of light and shadow in digital space.',
    width: 800,
    height: 600,
    category: 'Abstract',
    tags: ['digital', 'abstract', 'light'],
  },
  {
    id: 'art-2',
    src: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800&q=80',
    title: 'Urban Fragments',
    artist: 'James Park',
    year: '2024',
    description: 'Deconstructed cityscapes reimagined through computational photography.',
    width: 600,
    height: 800,
    category: 'Architecture',
    tags: ['urban', 'architecture', 'deconstruction'],
  },
  {
    id: 'art-3',
    src: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=800&q=80',
    title: 'Chromatic Aberration',
    artist: 'Sofia Reyes',
    year: '2023',
    description: 'Color theory meets digital distortion in this vibrant series.',
    width: 1200,
    height: 675,
    category: 'Generative',
    tags: ['color', 'distortion', 'generative'],
  },
  {
    id: 'art-4',
    src: 'https://images.unsplash.com/photo-1543857778-c4a1a3e0b2eb?w=800&q=80',
    title: 'Silent Frequencies',
    artist: 'Lucas Weber',
    year: '2024',
    description: 'Visual interpretations of sound wave patterns.',
    width: 675,
    height: 1200,
    category: 'Audio-Visual',
    tags: ['sound', 'frequency', 'minimal'],
  },
  {
    id: 'art-5',
    src: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&q=80',
    title: 'Neural Landscapes',
    artist: 'Maya Chen',
    year: '2024',
    description: 'AI-generated landscapes that blur the line between real and imagined.',
    width: 800,
    height: 800,
    category: 'AI Art',
    tags: ['ai', 'landscape', 'neural'],
  },
  {
    id: 'art-6',
    src: 'https://images.unsplash.com/photo-1550859492-d5da9d8e45f3?w=800&q=80',
    title: 'Temporal Shift',
    artist: 'Akira Tanaka',
    year: '2023',
    description: 'Time-based media exploring the concept of temporal displacement.',
    width: 900,
    height: 600,
    category: 'Media Art',
    tags: ['time', 'displacement', 'media'],
  },
  {
    id: 'art-7',
    src: 'https://images.unsplash.com/photo-1563089145-599f6741e507?w=800&q=80',
    title: 'Data Streams',
    artist: 'Elena Voss',
    year: '2024',
    description: 'Real-time data visualization as artistic expression.',
    width: 600,
    height: 900,
    category: 'Data Art',
    tags: ['data', 'visualization', 'real-time'],
  },
  {
    id: 'art-8',
    src: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&q=80',
    title: 'Material Studies',
    artist: 'James Park',
    year: '2023',
    description: 'Digital materials and their physical counterparts explored through photography.',
    width: 800,
    height: 600,
    category: 'Photography',
    tags: ['material', 'texture', 'study'],
  },
  {
    id: 'art-9',
    src: 'https://images.unsplash.com/photo-1604871000636-074fa5117945?w=800&q=80',
    title: 'Biomorphic Forms',
    artist: 'Nina Patel',
    year: '2024',
    description: 'Organic shapes emerging from algorithmic processes.',
    width: 700,
    height: 700,
    category: 'Generative',
    tags: ['organic', 'biomorphic', 'algorithmic'],
  },
  {
    id: 'art-10',
    src: 'https://images.unsplash.com/photo-1610824352934-c10d87b700cc?w=800&q=80',
    title: 'Light Fields',
    artist: 'Maya Chen',
    year: '2024',
    description: 'Volumetric light studies in virtual space.',
    width: 1000,
    height: 750,
    category: 'Abstract',
    tags: ['light', 'volumetric', 'space'],
  },
  {
    id: 'art-11',
    src: 'https://images.unsplash.com/photo-1551033406-611cf9a28f67?w=800&q=80',
    title: 'Geometric Intuition',
    artist: 'Lucas Weber',
    year: '2023',
    description: 'Pure geometric abstraction meets intuitive composition.',
    width: 750,
    height: 1000,
    category: 'Abstract',
    tags: ['geometric', 'abstraction', 'composition'],
  },
  {
    id: 'art-12',
    src: 'https://images.unsplash.com/photo-1561839561-b13bcfe9527b?w=800&q=80',
    title: 'Digital Fossils',
    artist: 'Sofia Reyes',
    year: '2024',
    description: 'Archaeological approach to digital artifact preservation.',
    width: 800,
    height: 600,
    category: 'Digital Art',
    tags: ['archaeology', 'fossils', 'digital'],
  },
  {
    id: 'art-13',
    src: 'https://images.unsplash.com/photo-1598899134736-5e2f0c4e1a0b?w=800&q=80',
    title: 'Wave Interference',
    artist: 'Akira Tanaka',
    year: '2024',
    description: 'Interference patterns generated by overlapping wave systems.',
    width: 1200,
    height: 800,
    category: 'Generative',
    tags: ['waves', 'interference', 'patterns'],
  },
  {
    id: 'art-14',
    src: 'https://images.unsplash.com/photo-1546548970-71785318a17b?w=800&q=80',
    title: 'Void Series No. 7',
    artist: 'Nina Patel',
    year: '2023',
    description: 'Exploring emptiness and negative space as primary compositional elements.',
    width: 600,
    height: 800,
    category: 'Minimal',
    tags: ['void', 'emptiness', 'negative-space'],
  },
  {
    id: 'art-15',
    src: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80',
    title: 'Cellular Automata',
    artist: 'Elena Voss',
    year: '2024',
    description: 'Emergent complexity from simple rule-based systems.',
    width: 800,
    height: 800,
    category: 'Generative',
    tags: ['cellular', 'automata', 'emergence'],
  },
  {
    id: 'art-16',
    src: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=800&q=80',
    title: 'Chromatic Fields',
    artist: 'Maya Chen',
    year: '2024',
    description: 'Large-scale color field studies rendered in real-time.',
    width: 1000,
    height: 600,
    category: 'Abstract',
    tags: ['color-field', 'real-time', 'chromatic'],
  },
];

export const SITE_CONFIG = {
  name: 'Infinite Gallery',
  tagline: 'Explore the endless digital exhibition',
  description: 'An infinite canvas portfolio experience',
  navigation: {
    items: [
      { label: 'Explorer', action: 'reset' },
      { label: 'About', action: 'about' },
      { label: 'Archive', action: 'archive' },
      { label: 'Contact', action: 'contact' },
    ],
  },
  aboutContent: {
    title: 'About the Gallery',
    body: 'An infinite digital exhibition space where artworks exist without boundaries or hierarchy. Each piece occupies its own coordinate in an endless two-dimensional plane, inviting exploration and discovery.',
    artists: [
      { name: 'Phakhin Nongthong', role: 'Street Photographer' },
    ],
  },
};